[build]
  publish = "/"
  command = "echo 'No build required'"

[forms]
  accept = ["contact", "kinetec-rental", "hometrainer-rental"]

# Headers optimized for Google Ads crawler compatibility
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "public, max-age=3600"
    X-Robots-Tag = "index, follow"